### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2021#13]
## Roadmap
- [ ] Levels
  - [x] Tilemap system
    - [ ] Tilemap sprites 
  - [ ] Doors between rooms
  - [ ] Level design 
- [ ] Game over
  - [x] Health system
    - [x] Health bars
    - [ ] Checkpoints that save the position
- [ ] Combat
  - [x] Weapon inventory with 4 slots
  - [ ] Gunplay
     - [ ] Bullet spread etc.
     - [ ] Reloading or overheating (optional)
  - [x] AMMO: Infinite
  - [ ] Powerups
    - [ ] Health
    - [ ] Speed
  - [ ] Gun content
     - [ ] Pistol: Glock, Baretta
     - [ ] Shotguns: Shoot multiple bullets at the same time
     - [ ] SMG
     - [ ] Assault rifles: AK-47, M416, M4A1
     - [ ] Machine gun
- [ ] AI / Enemies
  - [ ] Melee: runs to player (weak)
  - [ ] Range: average health average damage
  - [ ] Bosses: : different attacks & phases. Can e. g. unlock a new room

**Comment by rijkvp** [comment]
Dungeons: yes 
with doors between the rooms/dungeons

Health bars
Checkpoints: only position

Powerups: health, speed
Usable items: health
Items slots: at least 3 (can change later)
AMMO: Infinite
Gunplay: Maybe reloading or overheating

Gun types:
- Pistol: Glock, Baretta
- Shotguns: Shoot multiple bullets at the same time
- SMG: MP5
- Assault rifles: AK-47, M416, M4A1, Machine gun

Enemy types:
- Melee: runs to player (weak)
- Range: average health average damage

Range AI: keeps distance when in line of sight
 
Bosses: different attacks & phases

**Comment by rijkvp** [comment]
@max2032 & @antonhensen81 a created a little roadmap list to track our progress in this issue
